/* App */
export const ORIENTATION_CHANGE = 'ORIENTATION_CHANGE';
export const SAVE_INSTALL_PROMPT_EVENT = 'SAVE_INSTALL_PROMPT_EVENT';
export const INSTALL_SUCCESS = 'INSTALL_SUCCESS';

/* Auth */
export const AUTH_REQUEST = 'AUTH_REQUEST';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR';
export const CONFIRM_SIGN_UP_SUCCESS = 'CONFIRM_SIGN_UP_SUCCESS';
export const CONFIRM_SIGN_UP_ERROR = 'CONFIRM_SIGN_UP_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

/* User */
export const USER_REQUEST = 'USER_REQUEST';
export const GET_AUTH_USER_SUCCESS = 'GET_AUTH_USER_SUCCESS';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_ERROR = 'GET_USER_ERROR';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

/* Referrals */
export const REFERRALS_SET_SEARCH_TERM = 'REFERRALS_SET_SEARCH_TERM';
export const REFERRALS_FETCH_SUCCESS = 'REFERRALS_FETCH_SUCCESS';
export const REFERRALS_FETCH_ERROR = 'REFERRALS_FETCH_ERROR';
export const REFERRAL_CREATE_SUCCESS = 'REFERRAL_CREATE_SUCCESS';
export const REFERRAL_CREATE_ERROR = 'REFERRAL_CREATE_ERROR';

/* Database */
export const DATABASES_FETCH_SUCCESS = 'DATABASES_FETCH_SUCCESS';
export const DATABASES_FETCH_ERROR = 'DATABASES_FETCH_ERROR';
export const DATABASE_SELECT = 'DATABASE_SELECT';
export const DATABASE_CREATE_SUCCESS = 'DATABASE_CREATE_SUCCESS';
export const DATABASE_CREATE_ERROR = 'DATABASE_CREATE_ERROR';
export const DATABASE_DELETE_SUCCESS = 'DATABASE_DELETE_SUCCESS';
export const DATABASE_DELETE_ERROR = 'DATABASE_DELETE_ERROR';

/* Notification */
export const NOTIFICATIONS_FETCH_SUCCESS = 'NOTIFICATIONS_FETCH_SUCCESS';
export const NOTIFICATIONS_FETCH_ERROR = 'NOTIFICATIONS_FETCH_ERROR';
export const NOTIFICATION_CLEAR = 'NOTIFICATION_CLEAR';
export const NOTIFICATION_CLEAR_ALL = 'NOTIFICATION_CLEAR_ALL';

/* Error */
export const CLEAR_ERROR_STATE = 'CLEAR_ERROR_STATE';

/* Modal */
export const MODAL_OPEN = 'MODAL_OPEN';
export const MODAL_CLOSE = 'MODAL_CLOSE';
