// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_cognito_identity_pool_id': 'us-east-1:d7f7ffc9-fb91-4a55-8a80-73f0907727f3',
    'aws_cognito_region': 'us-east-1',
    'aws_project_id': 'f439d9c9-c4f6-407e-a7b6-8428c1f40824',
    'aws_project_name': 'lynx-pwa-2018-09-02-03-39-57',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'lynxpwa-mobilehub-1457567130',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_7nNDQSIVV',
    'aws_user_pools_web_client_id': '1mij6r6g52olpv9fhfr8s5g3p1',
}

export default awsmobile;
